apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crd.yaml
  - rbac.yaml
  - controller-deployment.yaml
  - nix-config.yaml
  - proxy-deployment.yaml

commonLabels:
  app.kubernetes.io/name: nix-remote-build-controller
  app.kubernetes.io/version: latest

