apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: builder-image-patch.yaml

images:
  - name: controller
    newName: ghcr.io/omarjatoi/nix-remote-build-controller/controller-x86_64
    newTag: latest
  - name: proxy
    newName: ghcr.io/omarjatoi/nix-remote-build-controller/proxy-x86_64
    newTag: latest
  - name: builder
    newName: ghcr.io/omarjatoi/nix-remote-build-controller/builder-x86_64
    newTag: latest
